//
// Created by F.Moitzi on 20.01.2022.
//

#ifndef SRC_LIB_MULTIPOLEMADELUNG_MULTIPOLEMOMENTS_HPP
#define SRC_LIB_MULTIPOLEMADELUNG_MULTIPOLEMOMENTS_HPP


class MultipoleMoments {

};


#endif //SRC_LIB_MULTIPOLEMADELUNG_MULTIPOLEMOMENTS_HPP
